services:
  # docker-compose build --progress plain
  # docker-compose run --rm protobufv3 /bin/bash
  # docker run --rm -it --platform linux/amd64 protobufv3:latest /bin/bash
  protobufv3:
    image: protobufv3:latest
    build: .
    working_dir: "/go/src/github.com/veqryn/awesome-go-api"
    volumes:
      - "./:/go/src/github.com/veqryn/awesome-go-api"

  openapiv2tov3:
    image: swaggerapi/swagger-codegen-cli-v3:3.0.62
    working_dir: "/opt/mnt"
    command:
      - "generate"
      - "-i"
      - "./protobufv3/openapiv2/gen/awesome.swagger.json"
      - "-l"
      #- "go"
      #- "openapi"
      - "openapi-yaml"
      - "-o"
      - "./protobufv3/openapiv3/gen/"
    volumes:
      - "./:/opt/mnt:Z"
