services:
  # docker-compose build --progress plain
  # docker-compose run --rm protobufv3 /bin/bash
  # docker run --rm -it --platform linux/amd64 protobufv3:latest /bin/bash
  protobufv3:
    image: protobufv3:latest
    build: .
    working_dir: "/go/src/github.com/veqryn/awesome-go-api"
    volumes:
      - "./:/go/src/github.com/veqryn/awesome-go-api"
      # For debugging bazel
      #- "./build/:/root/.cache"
