openapi: 3.0.3
info:
  title: My API
  version: 1.0.0
servers:
- url: /
paths:
  /error:
    get:
      operationId: get-error
      responses:
        "204":
          description: No Content
        default:
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
          description: Error
      summary: Get error
  /greeting/{name}:
    get:
      description: Respond with a greeting
      operationId: greeting
      parameters:
      - description: Name to greet
        example: world
        explode: false
        in: path
        name: name
        required: true
        schema:
          description: Name to greet
          example: world
          maxLength: 30
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetGreetingOutputBody'
          description: OK
        default:
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
          description: Error
      summary: Say hello to someone
      tags:
      - Greetings
  /reviews:
    post:
      operationId: post-review
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostReviewInputBody'
        required: true
      responses:
        "201":
          description: Created
        default:
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
          description: Error
      summary: Post a review
      tags:
      - Reviews
components:
  schemas:
    ErrorDetail:
      additionalProperties: false
      properties:
        location:
          description: "Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'"
          type: string
        message:
          description: Error message text
          type: string
        value:
          description: The value at the given location
      type: object
    ErrorModel:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          example: https://example.com/schemas/ErrorModel.json
          format: uri
          readOnly: true
          type: string
        detail:
          description: A human-readable explanation specific to this occurrence of
            the problem.
          example: Property foo is required but is missing.
          type: string
        errors:
          description: Optional list of individual error details
          items:
            $ref: '#/components/schemas/ErrorDetail'
          nullable: true
          type: array
        instance:
          description: A URI reference that identifies the specific occurrence of
            the problem.
          example: https://example.com/error-log/abc123
          format: uri
          type: string
        status:
          description: HTTP status code
          example: 400
          format: int64
          type: integer
        title:
          description: "A short, human-readable summary of the problem type. This\
            \ value should not change between occurrences of the error."
          example: Bad Request
          type: string
        type:
          default: about:blank
          description: A URI reference to human-readable documentation for the error.
          example: https://example.com/errors/example
          format: uri
          type: string
      type: object
    GetGreetingOutputBody:
      additionalProperties: false
      example:
        $schema: https://example.com/schemas/GetGreetingOutputBody.json
        message: "Hello, world!"
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          example: https://example.com/schemas/GetGreetingOutputBody.json
          format: uri
          readOnly: true
          type: string
        message:
          description: Greeting message
          example: "Hello, world!"
          type: string
      required:
      - message
      type: object
    PostReviewInputBody:
      additionalProperties: false
      example:
        $schema: https://example.com/schemas/PostReviewInputBody.json
        author: author
        rating: 1
        message: message
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          example: https://example.com/schemas/PostReviewInputBody.json
          format: uri
          readOnly: true
          type: string
        author:
          description: Author of the review
          maxLength: 10
          type: string
        message:
          description: Review message
          maxLength: 100
          type: string
        rating:
          description: Rating from 1 to 5
          format: int64
          maximum: 5
          minimum: 1
          type: integer
      required:
      - author
      - rating
      type: object
